### ISSUE TITLE
Wrong answer?

### ISSUE THREAD

**Issue by hans-aniket** [waithium/touch_typing_practise#2]
![Screenshot 2024-03-23 115836](https://github.com/waithium/touch_typing_practise/assets/129324778/9714a438-9b14-41da-a073-84514c53f8ae)
is there something i am doing wrong ?

**Comment by waithium** [comment]
' ; ' is also a character which needs to be typed.
Also, spaces between the alphabets (if any) should also be typed, as this exercise also aims to train the thumb (for the spacebar).

**Comment by hans-aniket** [comment]
oh, i get it.
